type: dlvae
in_channels: 3
num_hiddens: 128
num_embeddings: 512
embedding_dim: 16
sparsity_level: 3
num_residual_blocks: 2
num_residual_hiddens: 32
commitment_cost: 0.25
decay: 0.99
perceptual_weight: 0.5
learning_rate: 1e-4
beta: 0.9
compute_fid: false
log_images_every_n_steps: 100 