# configs/config.yaml
defaults:
  - _self_
  - model: dlvae
  - data: imagenette2
  - train: default
  - wandb: default
  - checkpoint: default

seed: 42
output_dir: outputs
hydra:
  run:
    dir: ${output_dir}/${now:%Y-%m-%d_%H-%M-%S}